name: Continuous Integration

on:
  push:
    paths:
      - "**.patch"
      - "**.txt"
      - "**.bash"
      - "**.yml"
  pull_request:
    paths:
      - "**.patch"
      - "**.txt"
      - "**.bash"
      - "**.yml"
  workflow_dispatch:

jobs:
  build-artifact:
    name: Build
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup environment
      run: sudo bash setup.bash

    - name: Setup Docker
      run: sudo bash setup-docker.bash

    - name: Extract
      run: bash extract.bash

    - name: Config and build
      run: bash build-switch-docker.bash

    - name: Package stdlib
      run: bash package-stdlib.bash

    - name: Upload stdlib artifact
      uses: actions/upload-artifact@v4
      with:
        name: python39-stdlib
        path: python39.zip

    - name: Upload prefix artifact
      uses: actions/upload-artifact@v4
      with:
        name: python39-switch
        path: python39-switch

  create-release:
    needs: build-artifact
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Download stdlib artifact
      uses: actions/download-artifact@v4
      with:
        name: python39-stdlib

    - name: Download prefix artifact
      uses: actions/download-artifact@v4
      with:
        name: python39-switch

    - name: Create release
      uses: marvinpinto/action-automatic-releases@v1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: ${{ contains(github.ref, '-rc') }}
        files: |
          python39-stdlib/*
          python39-switch/*
